name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  # add custom_lint and unmaterialistic
  custom_lint: any
  unmaterialistic:
    path: ../

flutter:
  uses-material-design: true
